### ISSUE TITLE
startSass/app/styles/components/class.scss .zero-bottom

### ISSUE THREAD

**Issue by 21DaysLearningCoding** [codingdogs/startSass#1]
## 416 line

```css
.zero-bottom {
    right: 0;
}
```

should be 

```css
.zero-bottom {
    bottom: 0;
}
```
